version: '3.9'

services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbapi
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - 3010:80
    environment:
      PMA_HOST: mariadb
    networks:
      - dev

  www:
    build: dockerphp
    container_name: back_symfony
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./dockerphp/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

  frontng:
    build:
      context: .
      dockerfile: Dockerfile.ng-front
    container_name: front_ng
    ports:
      - "4201:4200"
    volumes:
      - "/front/node_modules"
      - "./front:/front"

networks:
  dev:
